---
intro:
  title: Welcome & Practical Information
  sessions:
    - name: Welcome & Course Information
      description: "Start here; we will go over all the important things to know to get the most out of this workshop"
      speaker:
      type: Lecture
      support_channel: "#general"
      support_link: "https://gtnsmrgsbord.slack.com/archives/C01ES8R0RNG"
      faq: "https://docs.google.com/document/d/e/2PACX-1vTfNT2qS2Yb7qTAcnOFrMWwE_aPPUuYJJ0hdjw5gqV_JtMUWQ3NSkr6qAdrmF2EUGBBzTL8wFiILz8B/pub"

    - name: "Get set up for the course"
      description: "Here are the tasks you need to do ...."

    - name: "Meet & Join the Galaxy Community!"
      description: "This short video gives an overview of the worldwide Galaxy community, and different ways you can get involved! <strong>Video created by Beatriz Serrano-Solano</strong>."
      speaker: galaxycommunity
      video:
        link: -1MPdxmRs8U
        length: 5M
        captions: [shiltemann]
      material: &communitymaterial
        - type: GalaxyProject Home
          external: true
          title: galaxyproject.org
          link: "https://galaxyproject.org"
        - type: Galaxy servers
          external: true
          title: Find a Galaxy server near you!
          link: "https://galaxyproject.org/use/"
        - type: Galaxy Training Network
          external: true
          title: Start learning Galaxy
          link: "https://training.galaxyproject.org"
        - type: Support
          external: true
          link: "https://help.galaxyproject.org/"
          title: Galaxy Help Forum
        - type: Galaxy Publications
          external: true
          title: Zotero
          link: "https://www.zotero.org/groups/1732893/galaxy"
        - type: Galaxy Communities
          external: true
          title: Find and Join a community
          link: "https://galaxyproject.org/community/"
        - type: Events
          external: true
          link: "https://galaxyproject.org/events/"
          title: Galaxy Event Horizon
        - type: Mailing Lists
          external: true
          title: Stay informed of Galaxy activity!
          link: "https://galaxyproject.org/mailing-lists/"
        - type: Galaxy Working Groups
          external: true
          link: "https://galaxyproject.org/community/wg/"
          title: Find and join a WG
        - type: GitHub
          external: true
          link: "https://github.com/galaxyproject"
          title: galaxyproject
        - type: Gitter Chat
          external: true
          link: "https://gitter.im/galaxyproject/Lobby"
          title: Start talking with the Galaxy Community!
        - type: GTN Gitter
          external: true
          title: Join the training discussion here!
          link: "https://gitter.im/Galaxy-Training-Network/Lobby"
        - type: PaperCuts
          external: true
          title: Monthly Collaboration Fest
          link: "https://galaxyproject.org/events/2021-02-papercuts/"
        - type: GTN CoFest
          external: true
          title: Everybody Welcome!
          link: "https://github.com/galaxyproject/training-material/issues/1712"
        - type: Twitter
          external: true
          title: follow @galaxyproject
          link: "https://twitter.com/galaxyproject"
        - type: Twitter
          external: true
          title: follow the GTN @gxytraining
          link: "https://twitter.com/gxytraining"
tooldev:
  title: Galaxy Tool Development
  description: This module covers everything you need to start developing your own Galaxy Tools. This module will likely take you several days to complete.
  sessions:
    - name: Contributing to BioBlend Development
      type: Tutorial
      description: |
          This tutorial will teach you how to contribute to BioBlend and add support for a Galaxy API in BioBlend.
      speaker: [nsoranzo, rikeshi]
      material:
          - type: Tutorial
            link: /topics/dev/tutorials/bioblend-dev/tutorial.html

    - name: "Galaxy Tools: From Conda Through Deployment - Planemo Tool Init & Structure"
      description: |
          Here you will creating Galaxy tools from scratch using Conda for requirements, Planemo for testing, and Git for deployment.
      speaker: astrovsky01
      instructors: [davebx, bernt-matthias, astrovsky01]
      video:
        link: a6XZgEy6hlg
        length: 2M
        captions:
      material:
          - type: Tutorial
            link: /topics/dev/tutorials/tool-dev-from-scratch/tutorial.html
      support_channel: "#dev-tools-conda"
      support_link: "https://gtnsmrgsbord.slack.com/archives/dev-tools-conda"
      faq: "https://docs.google.com/document/d/1moSs0APNyhm4yZ9vPfpH0ErPONncNU-UCRzGvypc84I/pub"


    - name: "Galaxy Tools: From Conda Through Deployment - Writing the Wrapper"
      description: |
          Here you will creating Galaxy tools from scratch using Conda for requirements, Planemo for testing, and Git for deployment.
      speaker: astrovsky01
      instructors: [davebx, bernt-matthias, astrovsky01]
      video:
        link: FdtD8vBLK5k
        length: 17M
        captions:
      material:
          - type: Tutorial
            link: /topics/dev/tutorials/tool-dev-from-scratch/tutorial.html
      support_channel: "#dev-tools-conda"
      support_link: "https://gtnsmrgsbord.slack.com/archives/dev-tools-conda"
      faq: "https://docs.google.com/document/d/1moSs0APNyhm4yZ9vPfpH0ErPONncNU-UCRzGvypc84I/pub"


    - name: "Galaxy Tools: From Conda Through Deployment - Planemo Testing"
      description: |
          Here you will creating Galaxy tools from scratch using Conda for requirements, Planemo for testing, and Git for deployment.
      speaker: bernt-matthias
      instructors: [davebx, bernt-matthias, astrovsky01]
      video:
        link: 19mKUENz_i0
        length: 41M
        captions:
      material:
          - type: Tutorial
            link: /topics/dev/tutorials/tool-dev-from-scratch/tutorial.html
      support_channel: "#dev-tools-conda"
      support_link: "https://gtnsmrgsbord.slack.com/archives/dev-tools-conda"
      faq: "https://docs.google.com/document/d/1moSs0APNyhm4yZ9vPfpH0ErPONncNU-UCRzGvypc84I/pub"

    - name: "Galaxy Tools: From Conda Through Deployment - Contributing"
      description: |
          Here you will creating Galaxy tools from scratch using Conda for requirements, Planemo for testing, and Git for deployment.
      speaker: astrovsky01
      instructors: [davebx, bernt-matthias, astrovsky01]
      video:
        link: hg0YreA8W1I
        length: 30M
        captions:
      material:
          - type: Tutorial
            link: /topics/dev/tutorials/tool-dev-from-scratch/tutorial.html
      support_channel: "#dev-tools-conda"
      support_link: "https://gtnsmrgsbord.slack.com/archives/dev-tools-conda"
      faq: "https://docs.google.com/document/d/1moSs0APNyhm4yZ9vPfpH0ErPONncNU-UCRzGvypc84I/pub"





    - name: "ToolFactory: Generating Tools From Simple Scripts: Slides"
      description: |
          Here you'll get a quick overview about what the ToolFactory is and
          how it works.
      speaker: awspolly
      instructors: [fubar2]
      video:
        link: W5Ap5elAxQc
        length: 3M
        captions: [galaxycommunity]
      material:
          - type: Slides
            link: /topics/dev/tutorials/tool-generators/slides.html
      support_channel: "#dev-toolfactory"
      support_link: "https://gtnsmrgsbord.slack.com/archives/dev-toolfactory"
      faq: "https://docs.google.com/document/d/1e2iuYoseNkPvUBfMczEtPNsKI2Nfbyn6pN9Nz1x6E1o/pub"

    - name: "ToolFactory: Generating Tools From Simple Scripts: Quick Hands On"
      description: |
          Here you'll see how the ToolFactory works and get a quick tour of the hands on
      speaker: awspolly
      instructors: [fubar2]
      video:
        link: DK1eKz5TRs4
        length: 7M
        captions: [fubar2]
      material:
          - type: Tutorial
            link: /topics/dev/tutorials/tool-generators/tutorial.html
      support_channel: "#dev-toolfactory"
      support_link: "https://gtnsmrgsbord.slack.com/archives/dev-toolfactory"
      faq: "https://docs.google.com/document/d/1e2iuYoseNkPvUBfMczEtPNsKI2Nfbyn6pN9Nz1x6E1o/pub"

    - name: "ToolFactory: Generating Tools From Simple Scripts: Longer Hands-on"
      video:
        link: PJtjk6tVR2s
        length: 30M
        captions: [fubar2]
      description: |
          **Why this training might be useful:** If you write useful scientific
          analysis scripts, but have not yet learned to create new tools for
          Galaxy, the ToolFactory might help.

          It generates the XML "wrapper" for any simple, working command line
          script. The script, I/O and parameters are specified using a Galaxy
          tool form. When the form is completed, the tool it specifies is
          generated and installed, ready to run in the local Galaxy server.

          If a generated tool might be useful to other users, it can be linted
          and tested, producing a toolshed-ready archive for sharing.

          **Training model and support:** The ToolFactory training is designed
          for asynchronous self guided study. Developers have widely varying
          needs and interests. The ToolFactory is adaptable to almost any of
          these if a script is ready to wrap. No formal presentations are
          planned but the developer will be available during designated
          sessions to answer questions and learn about new bugs.

          **Resources:**
          1. Hello Galaxy video demonstration 10m (TBA)
          2. Tutorial: ["hello Galaxy" tools](https://training.galaxyproject.org/training-material/topics/dev/tutorials/tool-generators/tutorial.html)
          3. Tutorial: [Advanced features](https://training.galaxyproject.org/training-material/topics/dev/tutorials/tool-generators-advanced/tutorial.html)
          4. Sample tools in the Appliance history: The best way to learn what the ToolFactory can do is to rerun them with changes to the script, I/O and parameters to suit your needs.
          5. The ToolFactory Appliance is a flavour of docker-galaxy-stable for your private workstation or high-end laptop. Installation and disposal are described in the introductory tutorial.

          **Prerequisites:** Linux shell and scripting skills are required. A
          dedicated, private Linux workstation or high-end laptop is needed for
          Appliance installation.

          The ToolFactory is recommended for private desktop use only because
          executing unrestricted user installed tools is an unacceptable
          potential security risk for any production server.
      speaker: fubar2
      instructors: [fubar2]
      material:
          - type: Tutorial
            link: /topics/dev/tutorials/tool-generators/tutorial.html
      support_channel: "#dev-toolfactory"
      support_link: "https://gtnsmrgsbord.slack.com/archives/dev-toolfactory"
      faq: "https://docs.google.com/document/d/1e2iuYoseNkPvUBfMczEtPNsKI2Nfbyn6pN9Nz1x6E1o/pub"

    - name: BioBlend
      type: Tutorial
      description: Ever wondered how to interact with the Galaxy API to scale your work and automated processes? Learn how to here with BioBlend.
      speaker: [nsoranzo]

    - name: The GTN & Training Material Development
      type: Tutorial
      description:
      speaker: [shiltemann, bebatut, hexylena, slugger70]


    - name: "TBC: Galaxy Visualization Integration"
      type: Tutorial
      description:
      speaker: [dannon]

coredev:
  title: Galaxy Core Development
  description: This covers everything you need to start developing for Galaxy, understanding the codebase, adding APIs, implementing features. This module will likely take you several days to complete.
  sessions:
    - name: Galaxy architecture
      type: Lecture
      description:
      speaker: [jmchilton, natefoo, dannon]
    - name: Debugging and testing Galaxy core
      type: Tutorial
      description:
      speaker: [ic4f, assuntad23, jmchilton, mvdbeek]
    - name: Contributing extensions to Galaxy core (backend and frontend)
      type: Tutorial
      description:
      speaker: [jmchilton, dannon, ic4f, assuntad23, mvdbeek]
    - name: CYOA
      type: Tutorial
      description: Here you can pick a Galaxy bug that you find interesting, especially a 'paper-cut', and the instructors will help guide you to resolving this bug.

