name: Send to Slack

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5,15,25,35,45,55 * * * *'

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Send messages
        run: |
            cd slack-bot;
            bash cron.sh
            git add .
            count=$(git diff --name-only --cached | wc -l)
            if (( count > 0 )); then
                git config --global user.email "bot@github.com"
                git config --global user.name "Github Actions"
                git commit -a -m "[slack-bot] $(date '+%H:%M')"
                git push
            fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_URL: ${{ secrets.SLACK_API_ORGANISERS }}
